apiVersion: v1
kind: Config
clusters:
  - name: kdp
    cluster:
      certificate-authority-data: ${CA_CERT}
      server: ${KDP_SERVER}
contexts:
  - name: kdp
    context:
      cluster: kdp
      user: kdp-workspaces-operator
current-context: kdp
users:
  - name: kdp-workspaces-operator
    user:
      token: ${TOKEN}
