apiVersion: v1
kind: Secret
metadata:
  name: kdp-workspaces-operator-token
  namespace: kdp-workspaces-sa
  annotations:
    kubernetes.io/service-account.name: kdp-workspaces-operator
type: kubernetes.io/service-account-token
