apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  creationTimestamp: null
  name: maintainer-d.cncf.io
spec:
  resources:
  - group: maintainer-d.cncf.io
    name: collaborators
    schema: v251121-47720f8.collaborators.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: companies
    schema: v251121-47720f8.companies.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: maintainers
    schema: v251121-47720f8.maintainers.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: onboardingtasks
    schema: v251121-47720f8.onboardingtasks.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: projectmemberships
    schema: v251121-47720f8.projectmemberships.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: projects
    schema: v251121-47720f8.projects.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: services
    schema: v251121-47720f8.services.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: serviceteams
    schema: v251121-47720f8.serviceteams.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: serviceusers
    schema: v251121-47720f8.serviceusers.maintainer-d.cncf.io
    storage:
      crd: {}
  - group: maintainer-d.cncf.io
    name: serviceuserteams
    schema: v251121-47720f8.serviceuserteams.maintainer-d.cncf.io
    storage:
      crd: {}
status: {}
